// frontend-react/src/components/Login.tsx
import React from "react";
import { Link } from "react-router-dom";

import styles from "./Login.module.css";

interface Props {}
interface State {
    errorMessage: string;
}

export default class Login extends React.Component<Props, State> {
    state = {
        errorMessage: "",
    };

    onLogin = (event: any) => {
        event.preventDefault();

        if (event.target.elements.pass.value.length < 8) {
            this.setState({
                errorMessage: "Password should be at least 8 characters",
            });
            return;
        }
    };

    render() {
        return (
            <div className={styles.page_wrapper}>
                <div className={styles.left_side}>
                    <div className={styles.logo}>Modern Store</div>
                </div>
                <div className={styles.right_side}>
                    <form
                        onSubmit={this.onLogin}
                        className={styles.register_wrapper}
                    >
                        <h2 id={styles.heading}>Sign In</h2>
                        {this.state.errorMessage ? (
                            <p className={styles.error_message}>
                                {this.state.errorMessage}
                            </p>
                        ) : null}
                        <div className={styles.form_input}>
                            <label htmlFor="email">Email Address</label>
                            <input
                                required
                                type="email"
                                name="email"
                                id="email"
                                placeholder="example@email.com"
                            />
                        </div>
                        <div className={styles.form_input}>
                            <label htmlFor="pass">Password</label>
                            <input
                                required
                                type="password"
                                name="pass"
                                id="pass"
                                placeholder="********"
                            />
                        </div>
                        <button>Submit</button>
                        <p>
                            Not joined yet?{" "}
                            <Link to={{ pathname: "/register" }}>
                                {" "}
                                Register here
                            </Link>
                        </p>
                    </form>
                </div>
            </div>
        );
    }
}

// frontend-angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { UsersService } from '../services/users.service';
import { User } from '../models/users';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  public errorMessage: string = '';

  constructor(private usersService: UsersService) {}

  ngOnInit(): void {}

  onLogin(form: NgForm) {
    const user: User = {
      email: form.value.email,
      password: form.value.pass,
    };

    if (user.email === '' || user.password === '') {
      return;
    }

    this.usersService.loginUser(user);
  }
}

<div class="page_wrapper">
    <div class="left_side">
        <div class="logo">Modern Store</div>
    </div>
    <div class="right_side">
        <form class="register_wrapper" (ngSubmit)="onLogin(input)" #input="ngForm">
            <h2 id="heading">Sign In</h2>
            <p class="error_message">{{errorMessage}}</p>
            <div class="form_input">
                <label for="email">Email Address</label>
                <input ngModel required type="email" name="email" id="email" placeholder="example@email.com" />
            </div>
            <div class="form_input">
                <label for="pass">Password</label>
                <input ngModel required minlength="8" type="password" name="pass" id="pass" placeholder="password should be at least 8 characters" />
            </div>
            <button>Submit</button>
            <p>
                Not joined yet?
                <a routerLink="/register"> Sign Up here </a>
            </p>
        </form>
    </div>
</div>
